name: melon-ticket-check
on:
  schedule:
    - cron: '*/5 * * * *' # 5분마다 실행
jobs:
  check-ticket:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check Tickets
        uses: mooyoul/melon-ticket-actions@v1.1.0
        with:
          product-id: 211664           # Melon Ticket 공연 ID
          schedule-id: 100001          # 공연 일정 ID
          seat-id: 1_0                 # 좌석 ID
          slack-incoming-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          message: '<@U12345678> 티켓 열렸어요!'
